import { Activity, ArrowUpRight, Check, Database, FlaskConical, ShieldCheck, Wind } from 'lucide-react';
import type { Candidate } from './types';

interface Metrics { mae_cf_points:number; rmse_cf_points:number; r2:number; spearman:number|null; rows:number; plants:number; by_label_quality?:Record<string,Metrics> }
interface ModelResult { model:string; model_name?:string; grouped_cv:Metrics; spatial:Metrics; temporal:Metrics }
interface Evaluation { production_eligible:boolean; threshold_pct:number; improvement_pct:Record<string,number>; models:ModelResult[]; split_design:string; decision:string; protocol_version?:string; revision?:number; selected_model?:string; feature_order?:string[]; improvement_intervals?:Record<string,{lower_pct:number;upper_pct:number}>; intervals?:Record<string,{coverage:number;mean_width_cf_points:number}>; intervals_available?:boolean }
interface Summary { sample_unit?:string; label_description?:string; era5_note?:string; rows:number; plants:number; generators:number; date_start:string; date_end:string; label_quality:Record<string,number>; missingness:Record<string,number> }
interface Explanation { plant_id_eia:number; report_month:string; base_cf:number; actual_cf:number; predicted_residual_cf:number; bias_cf:number; factors:{feature:string;contribution_cf:number}[] }
export interface IntelligenceStatus { feature_enabled:boolean; model_available:boolean; model_loaded:boolean; model_version:string|null; status:string; reason:string; pipeline:null|{revision?:number;phase:string;detail:string;status:string;data?:Summary;phases:{phase:string;status:string;rows?:number;join_coverage?:number}[];evaluation?:Evaluation}; validation:Evaluation|null; training:Summary|null; explanations:Explanation[]; sources:{name:string;url:string}[] }
const format=(value:number|undefined,digits=1)=>value==null?'—':value.toLocaleString('en-US',{maximumFractionDigits:digits});
const modelName=(row:ModelResult)=>row.model==='selected'?`Selected ${row.model_name==='huber'?'Huber regression':row.model_name==='ridge'?'Ridge':'LightGBM'}`:({zero_residual:'Resource only',ridge:'Ridge baseline',random_forest:'Random Forest',lightgbm:'LightGBM Huber'} as Record<string,string>)[row.model]||row.model;
const label=(name:string)=>name.replace('isd_','').replace('resource_expected_capacity_factor','Resource baseline').replaceAll('_',' ');

export default function HistoricalPanel({status,onRefresh}:{status:IntelligenceStatus|null;onRefresh:()=>void}) {
 const report=status?.pipeline;const data=status?.training||report?.data;const evaluation=status?.validation||report?.evaluation;
 const rows=evaluation?.models||[];const baseline=rows.find(row=>row.model==='zero_residual');const model=rows.find(row=>row.model==='selected')||rows.find(row=>row.model==='lightgbm');
 const maximum=Math.max(1,...rows.flatMap(row=>[row.spatial.mae_cf_points,row.temporal.mae_cf_points]));
 const stopped=['gate_failed','rejected','error'].includes(status?.status||'');
 const example=status?.explanations?.[0];
 const plantLevel=data?.sample_unit==='plant-month'||(report?.revision||0)>=3;
 const selectedFeatures=evaluation?.feature_order||[];
 return <div className="historical-panel">
  <div className="historical-hero"><div className="historical-orbit"><Wind size={36}/></div><div><span className="overline">HISTORICAL PERFORMANCE / WIND</span><h2>From resource potential<br/>to observed performance.</h2><p>A measured correction learned from historical power output, resource profiles, and weather data.</p></div><span className={`pill ${status?.model_loaded?'green':stopped?'amber':''}`}>{status?.model_loaded?'Validated model':status?.model_available?'Validated model ready':stopped?'Quality gate stopped':status?.status==='running'?'Preparing data':'Base scoring active'}</span></div>
  <div className="historical-equation"><div><span>01 / RESOURCE</span><strong>Expected CF</strong><small>VCE RARE county baseline</small></div><b>+</b><div><span>02 / LEARNED</span><strong>Historical residual</strong><small>Actual output minus expectation</small></div><b>=</b><div><span>03 / SCREENING</span><strong>Corrected CF</strong><small>Only with validated, compatible inputs</small></div></div>
  <div className={`historical-status ${stopped?'is-stopped':''}`} role="status"><ShieldCheck size={22}/><div><strong>{status?.model_loaded?'Eligible model loaded':status?.model_available?'Validation passed; base rankings retained':stopped?'Base resource estimates are unchanged':'Corrections remain off until validation passes'}</strong><p>{report?.detail||status?.reason||'Reading model status…'}</p>{status?.model_available&&!status.feature_enabled&&<small>The trained model is ready. Live corrections stay off until matching candidate inputs are prepared within the validated geography and dates.</small>}</div><button className="button secondary" onClick={onRefresh}>Refresh<Activity size={14}/></button></div>
  {evaluation?.protocol_version&&<section className="historical-card"><div className="historical-card-title"><FlaskConical size={17}/><h3>Retrained with fresh holdouts</h3><span className="pill">Revision {evaluation.revision||2}</span></div><p>{plantLevel?'Reported wind-only plant output, broader geographic coverage, and wind features measured at 100 m height. Annual-only estimates and mixed-technology plants are excluded.':'Expanded western plant coverage, equal weight per plant, and geographic folds for model selection.'} Both final tests exclude previously examined plants. Test membership was frozen before tuning; each test is opened once.</p>{evaluation.improvement_intervals&&<p>95% uncertainty ranges for MAE improvement: {Object.entries(evaluation.improvement_intervals).map(([name,range])=>`${name} ${format(range.lower_pct)}% to ${format(range.upper_pct)}%`).join(' · ')}. {plantLevel?'Spatial ranges resample geographic blocks; temporal ranges resample plants.':'These plant-level bootstrap ranges describe uncertainty around the measured result.'}</p>}</section>}
  <div className="historical-stats"><div><span>{plantLevel?'Reported plant-months':'Generator-months'}</span><strong>{format(data?.rows,0)}</strong><small>{data?`${data.date_start} → ${data.date_end}`:'No training sample measured'}</small></div><div><span>Independent plants</span><strong>{format(data?.plants,0)}</strong><small>{data?`${format(data.generators,0)} generators`:'Grouped and spatial evaluation'}</small></div><div><span>Spatial improvement</span><strong>{evaluation?`${format(evaluation.improvement_pct.spatial)}%`:'—'}</strong><small>Spatial MAE · minimum 5%</small></div></div>
  <div className="historical-grid"><section className="historical-card"><div className="historical-card-title"><Database size={17}/><h3>Data quality, in the open</h3></div><div className="historical-label-row"><span><i className="gold-dot"/>Direct reported labels</span><b>{format(data?.label_quality.gold||0,0)}</b></div><div className="historical-label-row"><span><i className="silver-dot"/>PUDL calculated labels</span><b>{format(data?.label_quality.silver||0,0)}</b></div><p>{plantLevel?'Each plant receives equal total training weight. Labels use reported monthly wind generation and operating nameplate capacity.':evaluation?.protocol_version?'Each plant receives equal total training weight; calculated labels receive half the weight of direct labels.':'Estimated labels receive half weight.'} Plant identity, coordinates, and label quality never enter the predictive features.</p><div className="historical-checks">{report?.phases.map(phase=><div key={phase.phase}><Check size={13}/><span>{({V1:plantLevel?'Reported plant-month labels':'Clean generator-month labels',V2:'County-month resource join',V3:plantLevel?'Site weather coverage':'Ground-weather coverage',V4:'Complete feature table'} as Record<string,string>)[phase.phase]||phase.phase}</span><small>{phase.join_coverage!=null?`${format(phase.join_coverage*100)}%`:phase.rows?`${format(phase.rows,0)} rows`:'Passed'}</small></div>)}</div></section>
  <section className="historical-card"><div className="historical-card-title"><FlaskConical size={17}/><h3>Release criteria</h3></div><ol className="historical-criteria"><li>Plants stay together in validation folds.</li><li>Geographic blocks and a later year remain held out.</li><li>MAE improves by at least 5% on both holdouts.</li><li>The selected model matches or beats the development reference models.</li><li>Explanations reconcile; missing or unfamiliar inputs fall back.</li></ol></section></div>
  <section className="historical-card"><div className="historical-card-title"><Activity size={17}/><h3>Measured benchmark</h3><span className="muted small">Lower MAE is better · CF percentage points</span></div>{rows.length?<><div className="benchmark-bars">{rows.map(row=><div key={row.model}><strong>{modelName(row)}</strong><div className="benchmark-bar-pair"><div><i style={{width:`${row.spatial.mae_cf_points/maximum*100}%`}}/><b>{format(row.spatial.mae_cf_points,2)}</b></div><div><i className="temporal" style={{width:`${row.temporal.mae_cf_points/maximum*100}%`}}/><b>{format(row.temporal.mae_cf_points,2)}</b></div></div></div>)}</div><div className="benchmark-legend"><span><i/>Spatial holdout</span><span><i className="temporal"/>2023 temporal holdout</span></div><div className="benchmark-table-wrap"><table className="candidate-table"><thead><tr><th>Temporal test</th><th>MAE</th><th>RMSE</th><th>R²</th><th>Rank correlation</th></tr></thead><tbody>{[baseline,model].filter(Boolean).map(row=><tr key={row!.model}><td>{modelName(row!)}</td><td>{format(row!.temporal.mae_cf_points,2)}</td><td>{format(row!.temporal.rmse_cf_points,2)}</td><td>{format(row!.temporal.r2,3)}</td><td>{row!.temporal.spearman==null?'—':format(row!.temporal.spearman,3)}</td></tr>)}</tbody></table></div><p>{evaluation?.split_design}</p>{evaluation?.intervals&&<p>80% interval coverage: {Object.entries(evaluation.intervals).map(([key,value])=>`${key} ${format(value.coverage*100)}%`).join(' · ')}. {evaluation.intervals_available?'Intervals passed coverage checks.':'Intervals are withheld because coverage checks did not pass.'}</p>}</>:<div className="historical-empty"><FlaskConical size={28}/><strong>No benchmark reported yet</strong><p>{stopped?'The pipeline stopped before model evaluation. No performance numbers or ranking improvements have been invented.':'Training runs offline after the data-quality gates. This panel will show the measured comparison when available.'}</p></div>}</section>
  {example&&<section className="historical-card"><div className="historical-card-title"><Wind size={17}/><h3>Held-out explanation</h3><span className="muted small">Plant {example.plant_id_eia} · {example.report_month}</span></div><p>Resource baseline {format(example.base_cf*100)}% → predicted {format((example.base_cf+example.predicted_residual_cf)*100)}% CF. Actual reported CF: {format(example.actual_cf*100)}%. This is a held-out historical observation.</p><div className="historical-factors">{[...example.factors].sort((a,b)=>Math.abs(b.contribution_cf)-Math.abs(a.contribution_cf)).slice(0,4).map(f=><div key={f.feature}><span>{label(f.feature)}</span><strong className={f.contribution_cf>=0?'green-text':'amber-text'}>{f.contribution_cf>=0?'+':''}{format(f.contribution_cf*100,2)} points</strong></div>)}</div><small className="muted">SHAP describes model associations, not causal effects. The full contribution vector and model bias reconcile with its residual.</small></section>}
  <div className="historical-source-links">{status?.sources.map(source=><a key={source.name} href={source.url} target="_blank" rel="noreferrer">{source.name}<ArrowUpRight size={13}/></a>)}</div>
  {selectedFeatures.length>0&&<p className="historical-footnote">The selected model uses {selectedFeatures.length} inputs: county resource baseline, terrain, land cover, season{selectedFeatures.some(name=>name.startsWith('era5_'))?', and ERA5 weather':''}{selectedFeatures.some(name=>name.startsWith('isd_'))?', plus NOAA station observations':''}{selectedFeatures.some(name=>name.startsWith('gwa_'))?', plus local Wind Atlas climatology':''}. {(evaluation?.revision||0)>=4&&!selectedFeatures.some(name=>name.startsWith('gwa_'))?'Wind Atlas inputs were evaluated but were not selected.':''}</p>}
  {data?.era5_note&&<p className="historical-footnote">{data.era5_note} Wind power-curve features are screening approximations.</p>}
  {(evaluation?.revision||0)>=4&&<p className="historical-footnote">Fresh location tests cover Kansas, Oklahoma and Texas; historical inputs span 2019–2023. Current western-U.S. presets and 2024 inputs remain on base scoring.</p>}
  <p className="historical-footnote">This model does not predict project economics, grid curtailment, turbine layouts, or detailed plant operations. A RARE-trained residual is never silently applied to an incompatible resource baseline.</p>
 </div>;
}

export function CandidateIntelligence({candidate:c}:{candidate:Candidate}) {
 if(!c.ml_enabled&&!c.ml_fallback_reason)return null;
 return <section className="historical-card candidate-intelligence"><div className="historical-card-title"><Wind size={17}/><h3>Historical Intelligence</h3><span className="pill">{c.ml_enabled?`${c.ml_confidence} confidence`:'No correction applied'}</span></div>{c.ml_enabled?<><div className="historical-stats"><div><span>Base expected CF</span><strong>{format((c.ml_base_expected_cf||0)*100)}%</strong></div><div><span>Learned correction</span><strong>{(c.ml_predicted_residual_cf||0)>=0?'+':''}{format((c.ml_predicted_residual_cf||0)*100)}<small> points</small></strong></div><div><span>Corrected CF</span><strong>{format((c.ml_corrected_expected_cf||0)*100)}%</strong></div></div>{c.ml_interval_low_cf!=null&&c.ml_interval_high_cf!=null&&<p>80% interval: {format(c.ml_interval_low_cf*100)}–{format(c.ml_interval_high_cf*100)}% CF</p>}<div className="historical-factors">{c.ml_top_factors?.map(f=><div key={f.feature}><span>{label(f.feature)}</span><strong>{f.contribution_cf>=0?'+':''}{format(f.contribution_cf*100,2)} points</strong></div>)}</div><small className="muted">Model {c.ml_model_version} · bias {format((c.ml_explanation_bias_cf||0)*100,2)} CF points</small></>:<p>{c.ml_fallback_reason} The base resource estimate is retained.</p>}</section>;
}
