export type Technology = 'auto' | 'solar' | 'wind';
export type Region = 'california-nevada' | 'sacramento' | 'washington' | 'us';
export type WeightKey = 'resource' | 'environment' | 'grid' | 'buildability' | 'reuse';
export type Weights = Record<WeightKey, number>;
export interface Constraints { exclude_protected: boolean; max_grid_km: number; max_slope_deg: number; zero_new_land: boolean; min_capacity_mw: number }
export interface Polygon { type: 'Polygon'; coordinates: number[][][] }
export interface Plan { query: string; region: Region; technology: Technology; target_mw: number; weights: Weights; constraints: Constraints; mode: 'demo' | 'live'; polygon: Polygon | null; historical_intelligence?: boolean }
export interface Candidate extends HistoricalFields { screening_reasons?:string[]; surface_type?:'rooftop'|'parking_deck'|'parking_canopy';surface_area_m2?:number;usable_fraction?:number;building_height_m?:number;height_basis?:string;source_url?:string;roof_shape?:string;roof_pitch_deg?:number|null; id: string; site_id: string; name: string; technology: 'solar' | 'wind'; longitude: number; latitude: number; geometry: Polygon; capacity_mw: number; resource_value: number; resource_unit: string; grid_distance_km: number; slope_deg: number; protected_overlap_pct: number; developed_pct: number; natural_pct: number; developed_surface_verified: boolean; annual_gwh: number; components: Weights; confidence: string; provenance: string; evidence_ids: string[]; limitations: string[]; vintage: string; land_cover: string; score: number; rank: number; selected: boolean; exclusion_reasons?: string[]; excluded_land_cover?: boolean; metric_sources?: Record<string,{dataset:string;vintage:string}> }
export interface Dataset { id: string; name: string; provider: string; sensor: string; space_derived: boolean; access_method: string; asset_id: string | null; resolution_m: number | null; vintage: string; variables: string[]; metrics: string[]; energy_types: string[]; source_url: string; description: string; limitations: string }
export interface Portfolio { capacity_mw: number; target_mw: number; target_met: boolean; shortfall_mw: number; site_count: number; solar_mw: number; wind_mw: number; annual_gwh: number; mean_score: number; mean_grid_km: number }
export interface Verification { label: string; passed: boolean; detail: string }
export interface Telemetry { stage: string; provider: string; status: string; operation?: string; model?: string; latency_ms?: number; llm_latency_ms?: number; earth_engine_executions?: number; hybrid?: boolean }
export interface Result { city?:{scope?:'city'|'regional';radius_km?:number;name:string;state:string;geometry:GeoJSON.Polygon|GeoJSON.MultiPolygon;bounds:[number,number,number,number];limit:number;screened:number;eligible:number;excluded:number;target_specified:boolean;source_url:string;vintage:string}; urban_summary?:{comparison?:ApproachComparison[];recommended_approach?:string|null;urban_surfaces?:number;land_cells?:number;screened_options?:number;land_timestamp?:string;surface?:string;note:string;omitted:number;skipped:number;retrieved_at:string;source_timestamp:string}; stale?: boolean; run_id: string; plan: Plan; candidates: Candidate[]; excluded: Candidate[]; selected_ids: string[]; portfolio: Portfolio; verification: Verification[]; datasets: Dataset[]; explanation: string; telemetry: Telemetry[]; mode: 'demo' | 'live'; cache_hit: boolean; data_notice: string; duration_ms: number; analysis_timestamp: string; generated_at: string; }
export interface Health { services: Record<string,boolean>; live_ready: boolean; note: string }
export const REGIONS: Record<Region,{name:string;short:string;bounds:[number,number,number,number]}> = {
 'us':{name:'United States',short:'US city',bounds:[-180,18,180,72]},
 'california-nevada':{name:'Northern California + Nevada',short:'California + Nevada',bounds:[-123,37.3,-117,41.5]},
 'sacramento':{name:'Sacramento region',short:'Sacramento',bounds:[-122,38,-120.8,39.2]},
 'washington':{name:'Eastern Washington',short:'Eastern Washington',bounds:[-120.4,45.7,-117,48.5]},
};
export const DEFAULT_WEIGHTS: Weights = {resource:30,environment:30,grid:20,buildability:15,reuse:5};
export const DEFAULT_CONSTRAINTS: Constraints = {exclude_protected:true,max_grid_km:25,max_slope_deg:15,zero_new_land:false,min_capacity_mw:0};
export const DEFAULT_PLAN: Plan = {query:'Find the lowest-impact way to add 250 MW of sustainable energy in northern California and Nevada.',region:'california-nevada',technology:'auto',target_mw:250,weights:DEFAULT_WEIGHTS,constraints:DEFAULT_CONSTRAINTS,mode:'demo',polygon:null,historical_intelligence:false};

export interface HistoricalFields { ml_enabled?:boolean; ml_model_version?:string|null; ml_base_expected_cf?:number|null; ml_predicted_residual_cf?:number|null; ml_corrected_expected_cf?:number|null; ml_interval_low_cf?:number|null; ml_interval_high_cf?:number|null; ml_confidence?:'HIGH'|'MEDIUM'|'LOW'|null; ml_top_factors?:{feature:string;contribution_cf:number}[]|null; ml_training_similarity_score?:number|null; ml_fallback_reason?:string|null; ml_adjustment_cf?:number; ml_explanation_bias_cf?:number|null; base_resource_score?:number; base_annual_gwh?:number }

export const CITY_PLAN:Plan={...DEFAULT_PLAN,query:'Find the 5 best rooftops for solar in Sacramento, CA',region:'sacramento',technology:'solar',target_mw:1,mode:'live',constraints:{...DEFAULT_CONSTRAINTS,zero_new_land:true},polygon:{type:'Polygon',coordinates:[[[-121.505,38.575],[-121.485,38.575],[-121.485,38.59],[-121.505,38.59],[-121.505,38.575]]]}};

export interface ApproachComparison {id:string;label:string;screened:number;eligible:number;excluded:number;best_score:number|null;best_site_id:string|null;exclusions:{reason:string;count:number}[]}
export const REGIONAL_DEMO_PLAN:Plan={...CITY_PLAN,query:"What is the best way to increase renewable energy in Sacramento, CA and surrounding areas?",technology:"auto",constraints:{...DEFAULT_CONSTRAINTS},polygon:null};
